name = "obs-edge"
main = "src/index.ts"
compatibility_date = "2025-01-07"
compatibility_flags = ["nodejs_compat"]

# Production environment
[env.production]
name = "obs-edge-prod"
# Uncomment and configure when custom domain is ready:
# route = { pattern = "api.observability.genesis.com/*", zone_name = "genesis.com" }

# Development environment
[env.development]
name = "obs-edge-dev"

# KV namespace for rate limiting
# Create KV namespace: wrangler kv:namespace create RATE_LIMIT
[[kv_namespaces]]
binding = "RATE_LIMIT"
id = "placeholder" # Replace with actual KV namespace ID after creation

# Production KV
[[env.production.kv_namespaces]]
binding = "RATE_LIMIT"
id = "placeholder" # Replace with production KV namespace ID

# Environment variables
[vars]
ENVIRONMENT = "development"

[env.production.vars]
ENVIRONMENT = "production"

# Secrets (configure via wrangler secret put or GitHub Actions)
#
# Local development:
#   wrangler secret put SUPABASE_URL
#   wrangler secret put SUPABASE_SERVICE_KEY
#   wrangler secret put API_KEY
#
# GitHub Actions (use repository secrets):
#   CLOUDFLARE_API_TOKEN - for deployment
#   CLOUDFLARE_ACCOUNT_ID - your account ID
#
# Then set secrets via Wrangler CLI or Cloudflare Dashboard:
#   - SUPABASE_URL
#   - SUPABASE_SERVICE_KEY
#   - API_KEY
