name: obs-edge CI/CD

on:
  push:
    branches: [main]
    paths:
      - 'apps/obs-edge/**'
      - '.github/workflows/obs-edge-ci.yml'
  pull_request:
    branches: [main]
    paths:
      - 'apps/obs-edge/**'

jobs:
  test:
    name: Test obs-edge Worker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        working-directory: apps/obs-edge
        run: npm ci

      - name: Type check
        working-directory: apps/obs-edge
        run: npm run typecheck

      - name: Run tests
        working-directory: apps/obs-edge
        run: npm test

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: apps/obs-edge/coverage/

  deploy:
    name: Deploy to Cloudflare Workers
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        working-directory: apps/obs-edge
        run: npm ci

      - name: Deploy to Cloudflare Workers
        working-directory: apps/obs-edge
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: npx wrangler deploy

      - name: Deployment summary
        run: |
          echo "✅ obs-edge Worker deployed successfully!" >> $GITHUB_STEP_SUMMARY
          echo "🔗 Worker URL: https://obs-edge.YOUR_SUBDOMAIN.workers.dev" >> $GITHUB_STEP_SUMMARY
